config/routes.rb
Rails.application.routes.draw do
  resources :contents
  devise_for :users
  
  root 'pages#home'

  get 'about' => 'pages#about'

  post '/compra/:slug', to:'transactions#create', as: :compra
  get '/pickup/:guid', to:'transactions#pickup', as: :pickup
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
	
	extend FriendlyId
	  friendly_id :titolo, use: :slugged

	  belongs_to :user

	  has_many :sales

	  has_attached_file :cover
	  validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/,
	  message: "Solo le immagini sono supportate"

	  has_attached_file :allegato
	  validates_attachment_content_type :allegato, :content_type => [ /^image\/(png|gif|jpeg)/,'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/mspowerpoint','application/vnd.ms-powerpoint','application/vnd.openxmlformats-officedocument.presentationml.presentation', 'application/pdf', 'application/msexcel','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','audio/mpeg', 'audio/mp3' ],
	  message: "Formato non supportato"

	  validates :titolo, :descrizione, :price, presence: true
	  validates :price, numericality: { greater_than: 0.49 }
	  validates :cover, attachment_presence: true
	  validates :allegato, attachment_presence: true
end

app/models/sale.rb
class Sale < ApplicationRecord
	
	before_create :generate_guid
	belongs_to :content

		include AASM

		aasm column: 'state' do
			state :sleeping, initial: true
    		state :running
    		state :completed
    		state :errored

    		event :running, after: :charge_card do 
    			transitions from: :sleeping, to: :running	
			end 

			event :complete do 
				transitions from: :running, to: :completed
			end

			event :fail do 
				transitions from: :running, to: :errored
			end



		end		

		def charge_card

			begin
				save!
				charge = Stripe::Charge.create(
					amount: self.amount,
					currency: "eur",
					card: self.stripe_token,
					description: "Vendita di un contenuto"
					)
				self.update(stripe_id: charge.id)
				self.complete!

			rescue Stripe::StripeError => e
				self.update_attributes(error: e.message)
				self.fail!


			end

		end

		private

			def generate_guid
				self.guid = SecureRandom.uuid()
			end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	
	has_many :contents

	validates :name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_user, only:[:edit, :update, :distroy]



  def index
    @contents = Content.all.order("created_at DESC").paginate(page: params[:page], per_page: 6)
  end


  def show
  end


  def new
    @content = current_user.contents.build
  end

 
  def edit
  end

 
  def create
    @content = current_user.contents.build(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Il contenuto è stato creato con successo' }
      else
        format.html { render :new }
      end
    end
  end


  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Il contenuto è stato aggiornato con successo' }
      else
        format.html { render :edit }
      end
    end
  end


  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Il contenuto è stato eliminato' }
    end
  end

  private
    def set_content
      @content = Content.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def content_params
      params.require(:content).permit(:titolo, :descrizione, :price, :cover, :allegato)
    end

    def check_user
      if current_user != @content.user 
        redirect_to root_url, alert: "scusa ma non hai accesso a questa pagina"
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end

  def about
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

	def create
		content = Content.find_by!(slug: params[:slug])
		sale = content.sales.create(
			amount: (content.price * 100).floor, 
			email_acquirente: current_user.email,
			email_venditore: content.user.email,
			stripe_token: params[:stripeToken]
			)
		sale.running!

		if sale.completed?
			redirect_to pickup_url(guid: sale.guid)
		else
			redirect_to content_path(content), notice: @error
		end

	end

	def pickup
		@sale = Sale.find_by!(guid: params[:guid])
		@content = @sale.content
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contents/_form.html.erb
<%= form_for @content, html: { multipart: true } do |form| %>


  <% if content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
        <% content.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label class="grey-text">Carica il contenuto digitale che vuoi vendere (formati supportati: powerpoint, excel, pdf, word, immagini, mp3)</label><br>
    <%= form.file_field :allegato %>
  </div>
<br>
  <div class="field">
    <%= form.label :titolo %><br>
    <%= form.text_field :titolo %>
  </div>

  <div class="field">
    <%= form.label :descrizione %><br>
    <%= form.text_area :descrizione, class: "materialize-textarea" %>
  </div>

  <div class="field">
    <%= form.label :prezzo_min_50_cent %><br>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <label class="grey-text">Carica un immagine da utilizzare come cover per il tuo contenuto</label><br>
    <%= form.file_field :cover %>
  </div>
  <br>

  

  <div class="actions">
    <%= form.submit 'Salva Contenuto', class: "btn btn-form" %>
  </div>
  <br>
<% end %>

app/views/contents/edit.html.erb
<h1 class="center">Modifica Contenuto <%= @content.titolo%></h1>

<%= render 'form', content: @content %>

<%= link_to 'Mostra contenuto', @content %> |
<%= link_to 'Torna ai contenuti', contents_path %>

app/views/contents/index.html.erb
<!-- <h1>Contents</h1> -->


<div class="row">
  <% @contents.each do |content| %>
    <div class="col s3">
      <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
          <%= image_tag content.cover.url, class: "activator" %>
        </div>
        <div class="card-content">
          <span class="card-title activator grey-text text-darken-4"><%= content.titolo %><i class="material-icons right">more_vert</i></span>
          <div> 
            <span>Venduto da <%= content.user.name %></span>
            <span class="right"><%= number_to_currency(content.price) %></span>
          </div>
          <br>
            <div class="center"><%= link_to 'Scopri di più', content_path(content), class: "btn" %></div>
              <% if content.user == current_user %>
              <br>
              <div class="center">
                <p><%= link_to 'Edit', edit_content_path(content) %>
                <%= link_to 'Destroy', content, method: :delete, data: { confirm: 'sei sicuro di cancellare?' } %></p>
            </div>
          <% end %>
        </div>
        <div class="card-reveal">
          <span class="card-title grey-text text-darken-4"><%= content.titolo %><i class="material-icons right">close</i></span>
          <p><%= content.descrizione %></p>
        </div>
      </div> 
    </div>
  <% end %>
</div>

<br>

<div class="center">
  <%= will_paginate @contents %>
</div>

app/views/contents/new.html.erb
<h1 class="center">Vendi un contenuto digitale</h1>

<%= render 'form', content: @content %>

<%= link_to 'Torna ai contenuti', contents_path %>

app/views/contents/show.html.erb
<div class="row">
	<div class="col l6">
		<%= image_tag @content.cover.url, class: "responsive-img show-img" %>
	</div>
	<div class="col l6">
		<h1 class="show-titolo"><%= @content.titolo %></h1>
		<h4 class="show-prezzo"><%= number_to_currency(@content.price) %></h4>
		<p>Venduto da <%= @content.user.name %></p>
		<p><%= @content.descrizione %></p>

		<%if current_user %>
			<%= form_tag compra_path(slug: @content.slug) do %>
				<script 
					src="https://checkout.stripe.com/checkout.js"
				    class="stripe-button"
				    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
				    data-amount="<%= (@content.price * 100).floor %>"
				    data-name="MarkMarket"
				    data-description="<%= @content.titolo %>"
				    data-email="<%= @current_user.try(:email)%>"
				    data-currency="eur"
				    data-locale="auto">
			    </script>
			<%end%>

		<% else %>

			<p>Fai <%= link_to "Log In", new_user_session_path %> oppure <%= link_to "Registrati",  new_user_registration_path %> per acquistare questo contenuto</p>            
		
		<% end %>
	</div>
</div>






<% if @content.user == current_user %>
<%= link_to 'Edit', edit_content_path(@content) %> |
<% end %>
<%= link_to 'Torna ai contenuti', contents_path %>

app/views/layouts/_footer.html.erb
<footer class="page-footer #455a64 blue-grey darken-2">
  <div class="footer-copyright">
    <div class="container">
      <div class="row">

        <div class="col s4">
          © 2020 Mark Bartucca
        </div>
        <div class="col s4">
          Social
        </div>
        <div class="col s4">
          <%= link_to "About" , about_path, class: "grey-text text-lighten-4 right" %>       
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar-fixed">
  <nav class="#455a64 blue-grey darken-2">
        <div class="container nav-wrapper">
           <%= link_to "MarkMarket", root_path, class: "brand-logo" %>
          <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
              <ul class="right hide-on-med-and-down">
                <li><%= link_to 'Vendi contenuto', new_content_path %></li>
                  <% if user_signed_in? %>
                     <li><%= link_to "Log Out",  destroy_user_session_path, method: :delete %></li>
                  <% else %>
                      <li><%= link_to "Log In", new_user_session_path %></li>
                      <li><%= link_to "Sign up",  new_user_registration_path %></li>
                 <% end %>
              </ul>
        </div>
  </nav>
</header>
              <ul class="sidenav" id="mobile-demo" class="dropdown-trigger">
                <li><%= link_to 'Vendi contenuto', new_content_path %></li>
                  <% if user_signed_in? %>
                     <li><%= link_to "Log Out",  destroy_user_session_path, method:  :delete %></li>
                  <% else %>
                      <li><%= link_to "Log In", new_user_session_path %></li>
                      <li><%= link_to "Sign up",  new_user_registration_path %></li>
                    
                 <% end %>
              </ul>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarkMarket</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>
  <body>

    <%= render "layouts/header" %>

  <div class="conteniner">
    <% flash.each do |type, message| %>
    <script type="text/javascript">
        M.toast({html: '<%= message %>', 4000})
    </script>
  <% end %>

        
<main class="container">
    <%= yield %>
</main>
    <%= render "layouts/footer" %>

  </body>

      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script> 
      <script type="text/javascript"> 
        $(document).ready(function(){
        $('.sidenav').sidenav();
      });
      </script>

      <div class="container">
      <% flash.each do |type, message| %>
      <script>
        $(document).ready(function(){
          M.toast({html: "<%= message %>", classes: 'rounded <%= type %>'});
        });
      </script>
      </div>
  
  <% end %>

</html>

app/views/pages/about.html.erb
<h1>Chi Siamo</h1>
<p>Giovane impegnato</p>

app/views/pages/home.html.erb
<body>
      <h1 class="header center orange-text">MarkMarket</h1>
      <div class="row center">
        <h5 class="header col l12">Vendi e compra contenuti digitali</h5>
      </div>
      <div class="row center">
        <a href="http://localhost:3000/contents" id="download-button" class="btn-large waves-effect waves-light orange">Vai ai contenuti </a>
      </div>

  <div class="container">
    <div class="section">

      <!--   Icon Section   -->
      <br><br>
      <div class="row center">
        <h6 class="header col l12">Come funziona MarkMarket</h6>
      </div>
      <div class="row">
        <div class="col l4">
          <div class="icon-block">
            <h2 class="center light-blue-text"><i class="material-icons">flash_on</i></h2>
            <h5 class="center">Vantaggio 1</h5>

            <p class="light">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it </p>
          </div>
        </div>

        <div class="col l4">
          <div class="icon-block">
            <h2 class="center light-blue-text"><i class="material-icons">group</i></h2>
            <h5 class="center">Vantaggio 2</h5>

            <p class="light">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it </p>
          </div>
        </div>

        <div class="col l4">
          <div class="icon-block">
            <h2 class="center light-blue-text"><i class="material-icons">settings</i></h2>
            <h5 class="center">Vantaggio 3</h5>

            <p class="light">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it </p>
          </div>
        </div>
      </div>

    </div>
    <br><br>
  </div>

  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="js/materialize.js"></script>
  <script src="js/init.js"></script>

  </body>
</html>

app/views/transactions/pickup.html.erb
<h1>Grazie per aver acquistato</h1>

<p><%= link_to "Scarica qui", @content.allegato.url %> il tuo contenuto</p>